version: '3'
services:
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=password
    ports:
      - "127.0.0.1:3307:3306"
    volumes:
      - ./data:/var/lib/mysql
    command: mysqld --character-set-server=tis620 --collation-server=tis620_thai_ci
    restart: always
    container_name: mysql
