version: '2'
services:
  pantip-trend-visualization-mongodb:
    image: mongo:3
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./data:/data/db
    command: mongod  --storageEngine=wiredTiger
    restart: always
    container_name: pantip-trend-visualization-mongodb
